### ISSUE TITLE
Tiff writer tests produce a lot of stdout debug messages

### ISSUE THREAD

**Issue by royerloic** [ClearVolume/ClearCL#12]
Biformats is polluting the stdout, how can we stop this?

**Comment by haesleinhuepf** [comment]
It's hard but definitely possible. I'll invest some time soon.

**Comment by haesleinhuepf** [comment]
Workaround implemented in c6f05a9182153f9142f134114848e26edf89ca55

A better way would be to do this by implementing/initializing a correct slf4j Logger service and turning the logger of the usual way. But I believe this overshoots the issue as we don't need this logger service at all.
